### ISSUE TITLE
Placeholders

### ISSUE THREAD

**Issue by shatrovalexey** [SQLFTW/sqlftw#18]
For example
```
SELECT SQL_SMALL_RESULT
	`z`.`id` ,
	`z`.`title`
FROM
	(
		SELECT
			`y`.*
		FROM
			`x` AS `y`
	) AS `z`
WHERE
	( `z`.`title` = ? )
GROUP BY
	2
ORDER BY
	1 ASC ;
``` And I'll got message: "Placeholder ? is not allowed here.". But it isn't right as you see.
There may be next types of placeholders: "? , :name_value , @`name-value`, @name_value" AND `:"name-value"`.
Some times the placeholders with question sign may be named like "?name_value".

**Comment by paranoiq** [comment]
hi. this is what the actual MySQL server tells you when you run your SQL: `Syntax error near '? ) GROUP BY 2 ORDER BY 1 ASC' at line 12`

the reason is, that you are probably mistaking what is allowed in pure MySQL syntax and what is allowed in your client library/DBAL/ORM, which resolves value placeholders before sending the SQL to server (or creates a prepared statement). 

in SQL `?` placeholder is only allowed in prepared statement - e.g. `PREPARE stmt 'SELECT * FROM orders WHERE id = ?';`

if you want to enable client-side placeholders in Parser, this is how you do it (only these three types used by Doctrine
 are supported for now):
```
$session = new Session($platform, null, null, null,
        // UPDATE tbl1 SET col1 = ? WHERE col2 = ?;
    ClientSideExtension::ALLOW_QUESTION_MARK_PLACEHOLDERS_OUTSIDE_PREPARED_STATEMENTS
        // UPDATE tbl1 SET col1 = :val1 WHERE col2 = :val2;
    | ClientSideExtension::ALLOW_NAMED_DOUBLE_COLON_PLACEHOLDERS
        // UPDATE tbl1 SET col1 = ?1 WHERE col2 = ?2;
    | ClientSideExtension::ALLOW_NUMBERED_QUESTION_MARK_PLACEHOLDERS
);

$parser = new Parser($session);
```

![image](https://user-images.githubusercontent.com/146912/219880863-c23421e7-86c1-4a86-861d-77d7dbe5925b.png)

**Comment by shatrovalexey** [comment]
I've tested that and it worked as I ment.
```
use SqlFtw\{
	Platform\Platform ,
	Platform\ClientSideExtension ,
	Session\Session ,
	Parser\Parser
} ;

$plh = Platform::get( Platform::MYSQL , '5.7' ) ;
$seh = new Session( $plh , null , null , null , ClientSideExtension::ALLOW_NAMED_DOUBLE_COLON_PLACEHOLDERS ) ;
$pah = new Parser( $seh ) ;

$commands = $pah->parse( "
UPDATE `x` AS `z` SET `z`.`a` := :b ;
" ) ;

foreach ( $commands as list( $command ) ) {
	if ( ! method_exists( $command , 'getException' ) ) {
		continue ;
	}

	print_r( $command->getException( )->getMessage( ) ) ;
}
```
`Platform::get( Platform::MYSQL , '5.7' ) ;` but `new`.

Please, improve documentation to this project.
